# El enigma de la Flor Matakiterani: Desentrañando patrones matemáticos

En una misteriosa y enigmática isla, florece una planta única en el mundo: la Flor Matakiterani. Esta flor, venerada por los isleños, es famosa por su belleza excepcional y su patrón único de crecimiento en el número de pétalos. Según las leyendas locales, la Flor Matakiterani posee propiedades mágicas y curativas. Los habitantes de la isla han observado que estas flores pueden producir desde un mínimo de $6$ pétalos y hasta un asombroso máximo de $1001$ pétalos por día. En este taller, exploraremos las propiedades matemáticas de esta flor. 

1. La Flor Matakiterani sigue una secuencia específica en el número de pétalos que la flor produce cada día. Después de años de observación, los isleños han descubierto que la cantidad de pétalos que la flor produce en el $n$-ésimo día sigue la fórmula: $F_{n} = 5n + 1$, dónde $n$ corresponde al número de días. Calcula cuántos pétalos producirá la Flor Matakiterani en el día $10$.
1. ¿Cuántos días deben transcurrir para que la flor alcance su valor máximo de pétalos producidos?
1. ¿Existe un día en que la flor Matakiterani produzca $782$ pétalos? Explique.
1. Los isleños descubrieron otra flor cuyas propiedades parecen estar ligadas a otro tipo de secuencia. Durante los primeros $7$ días, esta flor crece de manera que el número de pétalos producidos en el $n$-ésimo día se duplica con respecto al día anterior. Si el primer día produce $4$ pétalos, construye la expresión algebraica $G_{n}$ que represente el número de pétalos producidos en el $n$-ésimo día e imprime ordenadamente la cantidad de pétalos producidos durante la primera semana.
1. Los isleños han notado que, luego de los primeros $7$ días, la magia de esta segunda flor pierde potencia, haciendo que el crecimiento sea más lento, modelado por la expresión: $$H_n = 5 \cdot (n - 8)\text{ para } n>7.$$ Calcula el total de pétalos producidos por esta segunda flor al finalizar un mes de $30$ días, considerando que comienza a florecer el día $1$.


In [ ]:
# --- Pregunta 1 ---

def F(n):
    return 5*n+1



print(f'En el dia 10 se producen {F(10)} petalos')




En el dia 10 se producen 51 petalos


En el dia 10 se producen 51 petalos

In [ ]:
# --- Pregunta 2 ---

maxPetalos = 1001


# 1001 = 5*n + 1
# 1000 / 5 = n
diaMax = 1000/5
print(f'La flor alcanza su maximo de petalos ({maxPetalos} petalos) en el dia {int(diaMax)}.')


# def maxP(maxPetalos=1001):
#     return (maxPetalos-1)//5

# print(maxP)




La flor alcanza su maximo de petalos (1001 petalos) en el dia 200


La flor alcanza su maximo de petalos (1001 petalos) en el dia 200

In [18]:
# --- Pregunta 3 ---

#Pertenece 782  a la sucecion ??
VALOR = 782

#Determinar si un determinado valor es término de la sucesión.
final=VALOR 
termino=0
n=0
dif=final-termino

while dif>0:
    n +=1
    termino=5*n + 1
    dif=final-termino

if dif==0:
    print(f'El {final} es un término de la sucesión y ocupa el lugar {n}')

else:
    print(f'El {final} no pertenece a la sucesión')







El 782 no pertenece a la sucesión


El 782 no pertenece a la sucesión

In [ ]:
# --- Pregunta 4 ---


# El primer dia hay 4 petalos 
#Sabemos que la razon es 2
# Tambien sabemos que es una PG


#A partir de esto concluimos que:
# La expresion del termino general es:  4*2**(n-1)


def G(n):
    4*2**(n-1)


for i in range(1,8):
    n=i
    print(f'En el dia {n} habran: {4*2**(n-1)} petalos')

En el dia 1 habran: 4 petalos
En el dia 2 habran: 8 petalos
En el dia 3 habran: 16 petalos
En el dia 4 habran: 32 petalos
En el dia 5 habran: 64 petalos
En el dia 6 habran: 128 petalos
En el dia 7 habran: 256 petalos


En el dia 1 habran: 4 petalos
En el dia 2 habran: 8 petalos
En el dia 3 habran: 16 petalos
En el dia 4 habran: 32 petalos
En el dia 5 habran: 64 petalos
En el dia 6 habran: 128 petalos
En el dia 7 habran: 256 petalos

In [ ]:
# --- Pregunta 5 ---
#Calcular la suma de los primeros 30 terminos.
#A partir del 8 dia (termino) la susecion se comporta: como H(n) = 5*(n - 8)   para todo n > 7.

def G(n):
    4*2**(n-1)

suma7Primeros=0
for i in range(1,8):
    n=i
    suma7Primeros = suma7Primeros + 4*2**(n-1)




suma8a30primeros=0
for i in range(8,31):
    n=i
    suma8a30primeros = suma8a30primeros + 5*(n - 8)



total30= suma7Primeros + suma8a30primeros

print(f'En el dia 30 habra un total de {total30} petalos.')


En el dia 30 habra un total de 1773 petalos


En el dia 30 habra un total de 1773 petalos